### ISSUE TITLE
Auth error again?

### ISSUE THREAD

**Issue by Sharppis1** [lostfields/python-panasonic-comfort-cloud#102]
Is it just me and my code which isn't working or anyone else have problems with authentication?

Basic authentication test with code example on readme.md returns also errors. 

--- Error finding meta_tag
Traceback (most recent call last):
    devices = client.get_devices()
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/apiclient.py", line 38, in get_devices
    self._get_groups()
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/apiclient.py", line 28, in _get_groups
    self._groups = self._auth.execute_get(
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 59, in execute_get
    return super().execute_get(url, function_description, expected_status_code)
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/authentication.py", line 389, in execute_get
    check_response(response, function_description, expected_status_code)
  File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/authentication.py", line 25, in check_response
    raise exceptions.ResponseError(
pcomfortcloud.exceptions.ResponseError: (get_groups: Expected status code 200, received: 401: {"code":"4100", "message": "Token expires"}

I haven't done any changes into my code and tried login from different locations to check if there's something with network. iOS app works fine. I can read that it says Token expires but isn't it suppose to renew if expired?

**Comment by LudovicRousseau** [comment]
I also have the same behaviour.
The token expires but a new one is generated. It will work fine the next time.

It would be better if this error is intercepted and pcomfortcloud tries again transparently after a new token is created.

**Comment by Sharppis1** [comment]
In my case it doesn't renew token. I call api every 30min, which has been interval in my case at least year now. At the moment I commented out that cronjob just to see if time would fix this 😬 I'm going to put it back "online" later and see what happens.

**Comment by xkram15** [comment]
Hi. I am currently also not able to use bacause of "**New version app has been published**" issue:

Traceback (most recent call last):
  File "/home/pi/python-panasonic-comfort-cloud/pcomfortcloud.py", line 301, in <module>
    main()
  File "/home/pi/python-panasonic-comfort-cloud/pcomfortcloud.py", line 214, in main
    session.start_session()
  File "/home/pi/python-panasonic-comfort-cloud/pcomfortcloud/apiclient.py", line 28, in start_session
    super().start_session()
  File "/home/pi/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 303, in start_session
    self._get_new_token()
  File "/home/pi/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 280, in _get_new_token
    check_response(response, 'get_acc_client_id', 200)
  File "/home/pi/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 27, in check_response
    f"{response.text}"
pcomfortcloud.exceptions.ResponseError: (get_acc_client_id: Expected status code 200, received: 401: {
  "code":4106,
  "message":"New version app has been published"

**Comment by Sharppis1** [comment]
Still login issue here also. Not 403 but 401. I left script alone for couple days and just tried it with no luck :/

**Comment by LudovicRousseau** [comment]
401 is Unauthorized.
You can try to login using the smartphone Comfort Cloud application to check your password is still valid. Maybe you have to accept new EULA, etc.

**Comment by xkram15** [comment]
Hi. Not a problem with a password (still using the same) and using app on a daily basis, so login there is working, not new EULA, nothing. Right now getting this error:

pi@automation:~ $ python3.7  /home/pi/python-panasonic-comfort-cloud/pcomfortcloud.py XXX@gmail.com XXX set --power On --temperature 18 -f Auto -m Cool -e Auto -y UpMid -x RightMid 1
--- Error finding meta_tag
Traceback (most recent call last):
  File "/home/pi/python-panasonic-comfort-cloud/pcomfortcloud.py", line 301, in <module>
    main()
  File "/home/pi/python-panasonic-comfort-cloud/pcomfortcloud.py", line 214, in main
    session.start_session()
  File "/home/pi/python-panasonic-comfort-cloud/pcomfortcloud/apiclient.py", line 28, in start_session
    super().start_session()
  File "/home/pi/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 301, in start_session
    self._refresh_token()
  File "/home/pi/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 333, in _refresh_token
    check_response(response, 'refresh_token', 200)
  File "/home/pi/python-panasonic-comfort-cloud/pcomfortcloud/session.py", line 27, in check_response
    f"{response.text}"
pcomfortcloud.exceptions.ResponseError: (refresh_token: Expected status code 200, received: 403: {"error":"invalid_grant","error_description":"Unknown or invalid refresh token."}

**Comment by Sharppis1** [comment]
> 401 is Unauthorized.
> 
> You can try to login using the smartphone Comfort Cloud application to check your password is still valid. Maybe you have to accept new EULA, etc.

I'm using app with same password with out any issues. I think EULA isn't issue either in my case.

**Comment by lostfields** [comment]
I can look into it, and I think we discussed a issue related to this earlier. Maybe there is an issue if the refresh token expires

**Comment by xkram15** [comment]
Yeah, I solved this just by downloading whore repository from github again and it works great again. 

What would be interesting to see why this came to this error from which the system cannot recover. It is still reproducible as I kept the original (now non-working) installation if needed for any test.

**Comment by lostfields** [comment]
The meta tag thingy should be solved by #105 . I close this now until we get more information related to 401/403
