### ISSUE TITLE
Unable to retrieve list of devices

### ISSUE THREAD

**Issue by didierm** [lostfields/python-panasonic-comfort-cloud#2]
I seem to be unable to retrieve a list of devices (username and password are correct ; a token is received) : 

```
$ python ./pcomfortcloud.py -t token.out $USR $PW list
```
```
list of devices and its device id #
Traceback (most recent call last):
  File "./pcomfortcloud.py", line 3, in <module>
    __main__.main()
  File "/tmp/scratch/development/panasonic/python-panasonic-comfort-cloud-master/pcomfortcloud/__main__.py", line 153, in main
    for idx, device in enumerate(session.get_devices()):
  File "/tmp/scratch/development/panasonic/python-panasonic-comfort-cloud-master/pcomfortcloud/session.py", line 153, in get_devices
    self._deviceIndexer[device['deviceHashGuid']] = device['deviceGuid']
KeyError: 'deviceHashGuid'
```

**Comment by lostfields** [comment]
Okey, are you using the PiPy package or Github? I can implement a raw dump to see if there is a difference in the output.

**Comment by lostfields** [comment]
I've added a `--raw true` flag to print out some raw text, it would be nice if you could paste them here or in a PM - or fix the problem by a pull requet :-)

**Comment by didierm** [comment]
_(some strings replaced with "**xxxxx**" for privacy's sake)_
```
$ python ./pcomfortcloud.py -r true -s true $USR $PW  list
--- token found
--- token probably expired
--- creating token by authenticating
--- raw beginning ---
{"uToken":"xxxxx","result":0,"language":0,"showFlg":0,"modeAvlList":{"avlFlg":false,"registerTime":null,"registerUsr":null,"country":23,"summerHouse":0,"iAutoX":1,"nanoe":0,"autoMode":1,"heatMode":1,"fanMode":1,"dryMode":1,"coolMode":1,"ecoNavi":0,"powerfulMode":1,"quietMode":1,"airSwingLR":0}}
--- raw ending    ---

--- _get_groups()
--- raw beginning ---
{"groupCount":1,"groupList":[{"groupId":4813,"groupName":"xxxxx","deviceIdList":[{"deviceGuid":"xxxxx","deviceType":"1","deviceName":"Airco-02-HK","permission":3,"summerHouse":0,"iAutoX":false,"nanoe":false,"autoMode":true,"heatMode":true,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"parameters":{"operate":0,"operationMode":3,"temperatureSet":27.0,"fanSpeed":0,"fanAutoMode":3,"airSwingLR":2,"airSwingUD":1,"ecoMode":0,"ecoNavi":1,"nanoe":0,"iAuto":0,"actualNanoe":0,"airDirection":0}},{"deviceGuid":"xxxxx","deviceType":"1","deviceName":"Airco-03-SK02","permission":3,"summerHouse":0,"iAutoX":false,"nanoe":false,"autoMode":true,"heatMode":true,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"parameters":{"operate":1,"operationMode":3,"temperatureSet":23.0,"fanSpeed":3,"fanAutoMode":1,"airSwingLR":1,"airSwingUD":0,"ecoMode":0,"ecoNavi":1,"nanoe":0,"iAuto":0,"actualNanoe":0,"airDirection":0}},{"deviceGuid":"xxxxx","deviceType":"1","deviceName":"Airco-04-SK03","permission":3,"summerHouse":0,"iAutoX":false,"nanoe":false,"autoMode":true,"heatMode":true,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"parameters":{"operate":0,"operationMode":3,"temperatureSet":30.0,"fanSpeed":0,"fanAutoMode":1,"airSwingLR":1,"airSwingUD":0,"ecoMode":0,"ecoNavi":1,"nanoe":0,"iAuto":0,"actualNanoe":0,"airDirection":0}},{"deviceGuid":"xxxxx","deviceType":"1","deviceName":"Airco-01-SK1","permission":3,"summerHouse":0,"iAutoX":false,"nanoe":false,"autoMode":true,"heatMode":true,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"parameters":{"operate":1,"operationMode":3,"temperatureSet":30.0,"fanSpeed":0,"fanAutoMode":0,"airSwingLR":2,"airSwingUD":0,"ecoMode":2,"ecoNavi":1,"nanoe":0,"iAuto":0,"actualNanoe":0,"airDirection":0}}]}]}
--- raw ending    ---

list of devices and its device id (1-x)
Traceback (most recent call last):
  File "./pcomfortcloud.py", line 3, in <module>
    __main__.main()
  File "/home/didier/development/panasonic/python-panasonic-comfort-cloud-master/pcomfortcloud/__main__.py", line 173, in main
    for idx, device in enumerate(session.get_devices()):
  File "/home/didier/development/panasonic/python-panasonic-comfort-cloud-master/pcomfortcloud/session.py", line 175, in get_devices
    self._deviceIndexer[device['deviceHashGuid']] = device['deviceGuid']
KeyError: 'deviceHashGuid'
```

**Comment by lostfields** [comment]
I've pushed a new version, may you try this one? 

I don't have Python 2.7 so I'm unsure if `hashlib.md5(device['deviceGuid'].encode('utf-8')).hexdigest()` works out. My devices returns a `deviceHashGuid` and your response doesn't have that, so we have to create a unique string (and I don't like the format of the deviceGuid).

**Comment by didierm** [comment]
New version works with both python2 (v2.7.15) and python3 (v3.7.1) ; thanks !

The parameter "**-s true**" is required, to prevent
`requests.exceptions.SSLError: HTTPSConnectionPool(host='accsmart.panasonic.com', port=443): Max retries exceeded with url: /device/group (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)')))`

(there are some other issues, which I'll report in separate reports)
