### ISSUE TITLE
Unsupported Nanoe-mode

### ISSUE THREAD

**Issue by lostfields** [lostfields/python-panasonic-comfort-cloud#29]
I just downloaded and tried this module and after some initial troubles I got it to work.  I can similarly use list and set but the get command comes up with a different error:

```
matth@Ubuntu:~$ sudo python3 .local/bin/pcomfortcloud 'email@inter.net' 'password' get 1
reading from device 'Study' (8b9ba922de8289714a5b9d9a12377c04)
Traceback (most recent call last):
  File ".local/bin/pcomfortcloud", line 11, in <module>
    load_entry_point('pcomfortcloud==0.0.15', 'console_scripts', 'pcomfortcloud')()
  File "/home/matth/.local/lib/python3.6/site-packages/pcomfortcloud/__main__.py", line 218, in main
    print_result( session.get_device(device['id']) )
  File "/home/matth/.local/lib/python3.6/site-packages/pcomfortcloud/session.py", line 285, in get_device
    'parameters': self._read_parameters(_json['parameters'])
  File "/home/matth/.local/lib/python3.6/site-packages/pcomfortcloud/session.py", line 436, in _read_parameters
    value['nanoe'] = constants.NanoeMode(parameters['nanoe'])
  File "/usr/lib/python3.6/enum.py", line 293, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.6/enum.py", line 535, in __new__
    return cls._missing_(value)
  File "/usr/lib/python3.6/enum.py", line 548, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 4 is not a valid NanoeMode
```
Is this related or is it a different error?

_Originally posted by @MatthK in https://github.com/lostfields/python-panasonic-comfort-cloud/issues/26#issuecomment-684924531_

**Comment by lostfields** [comment]
https://github.com/lostfields/python-panasonic-comfort-cloud/issues/26#issuecomment-685677597

**Comment by lostfields** [comment]
This is a model supporting Nanoe-X and Nanoe-G, and both is hold by parameter `nanoe` with value 3 og 4. One of them is both Nanoe-X and Nanoe-G, and the other is only Nanoe-G.


> nanoe-G and nanoe-X air-purifying operation can be activated independently
> 
> Advance nanoeX air-purifying system has a better performance in odor removal, such as cigarette, sweat and pet smell, virus, bacteria and allergen inhibition.
> 
> nanoe-G Air Purifying System inactivates 99% PM2.5, airborne and adhesive micro-organisms such as bacteria, viruses and mould, and comes with In-filter Deactivation feature
