### ISSUE TITLE
Got a 403 response

### ISSUE THREAD

**Issue by TrueCrashB** [lostfields/python-panasonic-comfort-cloud#39]
Hi, i would like to use your script. i have 3 Panasonic ACs
I tried to connect but got a 403 response

./pcomfortcloud -s true "myID" "myPW" list

Traceback (most recent call last):
  File "./pcomfortcloud", line 10, in <module>
    sys.exit(main())
  File "/home/openhabian/.local/lib/python3.7/site-packages/pcomfortcloud/__main__.py", line 200, in main
    session.login()
  File "/home/openhabian/.local/lib/python3.7/site-packages/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/home/openhabian/.local/lib/python3.7/site-packages/pcomfortcloud/session.py", line 131, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 403 - Data: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

Greetings
Marc

**Comment by TomS1985** [comment]
Panasonic changed the version from 1.9.0 to 1.10.0, so the version has to be changed in pcomfortcloud/session.py from 1.9.0 to 1.10.0. After this, it works again (in my case)

**Comment by lostfields** [comment]
Version is fixed in issue #38 and release as version 0.0.20

**Comment by TrueCrashB** [comment]
Thx, a lot!
It worx!
Great job!

**Comment by MatthK** [comment]
Awesome. Highly appreciated.
