### ISSUE TITLE
403

### ISSUE THREAD

**Issue by k1ng440** [lostfields/python-panasonic-comfort-cloud#43]
```
> pcomfortcloud xxxx@gmail.com xxxxxx list
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\st431\AppData\Roaming\Python\Python39\Scripts\pcomfortcloud.exe\__main__.py", line 7, in <module>
  File "C:\Users\st431\AppData\Roaming\Python\Python39\site-packages\pcomfortcloud\__main__.py", line 202, in main
    session.login()
  File "C:\Users\st431\AppData\Roaming\Python\Python39\site-packages\pcomfortcloud\session.py", line 99, in login
    self._create_token()
  File "C:\Users\st431\AppData\Roaming\Python\Python39\site-packages\pcomfortcloud\session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 403 - Data: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
```

**Comment by k1ng440** [comment]
adding `user-agent: G-RAC` solves the issue

**Comment by k1ng440** [comment]
please review #44

**Comment by sygys** [comment]
Got the same problem. Panasonic must have changed something in their api, my airco only shows unavailable in home assistant as of today.

We need a more steady solution. Isnt there a way to fool the wifi module and keep everything local. Im not planning on fixing these problems every so many days if panasonic decides to change the api again.

**Comment by lostfields** [comment]
Panasonic API isn't public, that's why it is what it is.
