### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by MrKitchy** [lostfields/python-panasonic-comfort-cloud#45]
Have panasonic updates something again?
I'm getting forbidden constantly now:

Traceback (most recent call last):
  File "main.py", line 137, in <module>
    heat_pumps_status = get_panasonic_cloud_status()
  File "main.py", line 86, in get_panasonic_cloud_status
    panasonic_session.login()
  File "C:\Program Files (x86)\Python 3.7\lib\site-packages\pcomfortcloud\session.py", line 99, in login
    self._create_token()
  File "C:\Program Files (x86)\Python 3.7\lib\site-packages\pcomfortcloud\session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 403 - Data:
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

**Comment by lostfields** [comment]
PR #44 should solve this, Panasonic has implemented a user-agent block now. Published as version 0.0.21
