### ISSUE TITLE
expired token

### ISSUE THREAD

**Issue by git2206** [lostfields/python-panasonic-comfort-cloud#53]
hi,

script was working fine in the last weeks...
but now i got error message..
Traceback (most recent call last):
  File "./pcomfortcloud.py", line 5, in <module>
    __main__.main()
  File "/opt/scripts/python-panasonic-comfort-cloud-master/pcomfortcloud/__main__.py", line 202, in main
    session.login()
  File "/opt/scripts/python-panasonic-comfort-cloud-master/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/opt/scripts/python-panasonic-comfort-cloud-master/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 401 - Data: {"message":"New version app has been published","code":4106}

can you check this?

THX

**Comment by lostfields** [comment]
Hi, version 0.0.22 should fix this

**Comment by git2206** [comment]
BIG THxs!
its working!

br
Flo
