### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by thxraph** [lostfields/python-panasonic-comfort-cloud#71]
Hello, here is the error message, where can we find the new version number like in July and edit the file?

python aircon_mqtt.py
Traceback (most recent call last):
  File "/root/aircon_mqtt.py", line 10, in <module>
    session.login()
  File "/usr/local/lib/python3.9/dist-packages/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/usr/local/lib/python3.9/dist-packages/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 401 - Data: {"message":"New version app has been published","code":4106}

Thank you!
Raphael

**Comment by lostfields** [comment]
Great, current version set by this lib is 1.19 so it should be ok
